---
domain:           "mse.jhu.edu"
db_ip:            "10.162.127.103"
db_hostname:      "psql03"
app_ip:           "10.162.127.158"
app_hostname:     "dspace-prod"
db_pass:          "{{ vault_db_pass }}"
tomcat_pass:      "{{ vault_tomcat_pass }}"

# email vars:
mail_server:  "{{ vault_mail_server }}"
mail_admin:   "{{ vault_mail_admin }}"

# admin vars:
admin_email:      "{{ vault_admin_email }}"
admin_firstname:  "{{ vault_admin_firstname }}"
admin_lastname:   "{{ vault_admin_lastname }}"
admin_password:   "{{ vault_admin_password }}"
admin_language:   "English"
# members of this list will not be anonymized (no additional permissions granted):
admin_users: "{{ vault_admin_users }}"

# SSL vars
self_sign_cert:             false
ssl_certificate_file:       "star_mse.jhu.edu.crt"
ssl_certificate_key_file:   "star_mse.jhu.edu.key"
ssl_certificate_chain_file: "star_mse.jhu.edu_interim.crt"
ssl_certificate_path:       "/etc/pki/tls/certs"
ssl_certificate_key_path:   "/etc/pki/tls/private"
ssl_certificate_subj:       ""

# SSH vars
environ:                "prod" # dev || stage || prod
login_user_key:         "dspace_prod"
create_login_user_key:  false

# deployment vars
# ---------------
reloadable: false
caching_allowed: true
# TODO: currently set to self. adjust.
restricted_ip_range: "10.162.127.158"
production: True # TODO: use or lose

# assetstore vars
# ---------------
stores_available: true
stores_fstab: "sam.mse.jhu.edu:/apps/dspace"

# old prod vars
remote_host:      "xen02.mse.jhu.edu"
remote_user:      "dspace15"
remote_database:  "dspace15"
remote_password:  "{{ vault_remote_password }}"
remote_backup:    "jscholarship_backup.sql"
