---
- name: instal EPEL repo
  yum: name=epel-release state=present
  become: yes
  become_user: root

- name: install prereqs for ansible control of postgres
  yum: name={{ item }} state=present enablerepo=epel
  become: yes
  become_user: root
  with_items:
    - postgresql-libs
    - python-psycopg2
