---
- name: adjust pgpass 
  lineinfile:
    dest: "/home/{{ admin_user }}/.pgpass"
    regexp: "^localhost:\\*:{{ database }}:"
    line:    "localhost:*:{{ database }}:{{ user }}:{{ password }}"
    state: "{{ state }}"
    create: yes
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: "0600"
