---
- name: maven package
  become: yes
  become_user: "{{ app_user }}"
  shell: "source /etc/profile && mvn package -Dmirage2.on=true -Dmirage2.deps.included=false"
  args:
    chdir: "{{ dspace_source }}/dspace"
  register: result

  # TODO: remove -Doverwrite=false after testing
- name: ant update configs
  become: yes
  become_user: "{{ app_user }}"
  shell: bash -lc "ant update_configs -Doverwrite=false"
  args:
    chdir: "{{ dspace_source }}/dspace/target/dspace-installer"
  when: result
