---
domain:           "jhu.dev"
db_ip:            "10.10.20.102"
db_hostname:      "dspace-db-dev"
app_ip:           "10.10.20.101"
app_hostname:     "dspace-dev"
db_pass:          "{{ vault_db_pass }}"
tomcat_pass:      "{{ vault_tomcat_pass }}"

# email vars:
mail_server: "{{ vault_mail_server }}"
mail_admin: "{{ vault_mail_admin }}"

# admin vars:
admin_email: "{{ vault_admin_email }}"
admin_firstname: "{{ vault_admin_firstname }}"
admin_lastname: "{{ vault_admin_lastname }}"
admin_password: "{{ vault_admin_password }}"
admin_language: "English"

# SSL vars
self_sign_cert:             true
ssl_certificate_file:       "{{ app_fqdn | replace('.', '_') }}.crt" # "star_library_jhu_edu.crt"
ssl_certificate_key_file:   "{{ app_fqdn | replace('.', '_') }}.key" # "star_library_jhu_edu.key"
ssl_certificate_chain_file: false                # "star_library_jhu_edu_interm.crt"
ssl_certificate_path:       "/etc/pki/tls/certs"
ssl_certificate_key_path:   "/etc/pki/tls/private"
ssl_certificate_subj:       "/C=US/ST=Maryland/L=Baltimore/O=JHU/CN={{ app_fqdn }}"
