---
# TODO: generalize
- name: create anonymized backup of production database
  hosts: db_servers
  become: yes
  become_user: "{{ login_user }}"

  vars:
    anon_db: "dspace-anon"
    backup_file: "{{ production_backup }}"

  handlers:
    - include: handlers/reload_postgres.yml

  tasks:
    # - name: install ansible postgres prereqs
    #   include: tasks/ansible_postgres_prereqs.yml

    - name: add pg_hba entry for production database
      include: tasks/pg_hba_entry.yml
      vars:
        connection_type: "local"
        database: "{{ db_name }}"
        user: "{{ db_user }}"
        auth_method: "md5"
        state: "present"

    - name: add pg_hba entry for anonymized database
      include: tasks/pg_hba_entry.yml
      vars:
        connection_type: "local"
        database: "{{ anon_db }}"
        user: "{{ db_user }}"
        auth_method: "md5"
        state: "present"

    - name: add pgpass entry for anonymized database
      include: tasks/pgpass.yml
      vars:
        admin_user: "{{ login_user }}"
        admin_group: "{{ login_group }}"
        database: "{{ anon_db }}"
        user: "{{ db_user }}"
        password: "{{ db_pass }}"
        state: "present"

    - name: add pgpass entry for production database
      include: tasks/pgpass.yml
      vars:
        admin_user: "{{ login_user }}"
        admin_group: "{{ login_group }}"
        database: "{{ db_name }}"
        user: "{{ db_user }}"
        password: "{{ db_pass }}"
        state: "present"

    - name: backup production database
      include: tasks/backup_db.yml
      vars:
        database: "{{ db_name }}"
        user: "{{ db_user }}"
        file: "{{ backup_file }}"

    - name: restore anonymized database from production database
      include: tasks/restore_db.yml
      vars:
        database: "{{ anon_db }}"
        user: "{{ db_user }}"
        file: "{{ backup_file }}"

    - name: run query to anonymize database
      include: tasks/query_db.yml
      vars:
        admin_user: "{{ login_user }}"
        admin_group: "{{ login_group }}"
        database: "{{ anon_db }}"
        user: "{{ db_user }}"
        query_file: "queries/anonymize_db.sql"

    - name: backup anonymized database
      include: tasks/backup_db.yml
      vars:
        database: "{{ anon_db }}"
        user: "{{ db_user }}"
        file: "{{ anonymized_backup }}"

    - name: drop anonymized database
      postgresql_db:
        name: "{{ anon_db }}"
        state: "absent"
      become_user: "{{ postgres_user }}"

    - name: remove pg_hba entry for anonymized database
      include: tasks/pg_hba_entry.yml
      vars:
        connection_type: "local"
        database: "{{ anon_db }}"
        user: "{{ db_user }}"
        auth_method: "md5"
        state: "absent"

    # TODO: review
    - name: remove pg_hba entry for production database
      include: tasks/pg_hba_entry.yml
      vars:
        connection_type: "local"
        database: "{{ db_name }}"
        user: "{{ db_user }}"
        auth_method: "md5"
        state: "absent"

    - name: remove pgpass entry for anonymized database
      include: tasks/pgpass.yml
      vars:
        admin_user: "{{ login_user }}"
        admin_group: "{{ login_group }}"
        database: "{{ anon_db }}"
        user: "{{ db_user }}"
        password: "{{ db_pass }}"
        state: "absent"

    - name: remove pgpass entry for production database
      include: tasks/pgpass.yml
      vars:
        admin_user: "{{ login_user }}"
        admin_group: "{{ login_group }}"
        database: "{{ db_name }}"
        user: "{{ db_user }}"
        password: "{{ db_pass }}"
        state: "absent"

    # NOTE: since we can use the production backup in the new production env
    # and the anonymized backup elsewhere, let's keep them both (for now)
    # - name: remove the production backup file from the server
    #   file:
    #     path: "{{ backup_file }}"
    #     state: absent
