---
- hosts: db_servers
  become: true

  vars_files:
    - ../vars/main.yml
  vars:
    db_hostname_arg:  "-dh {{ ansible_hostname }}"
    domain_arg:       "-d {{ domain }}"
    db_ip_arg:        "-di {{ ansible_eth1.ipv4.address }}"
    db_name_arg:      "-dn {{ db_name }}"
    db_user_arg:      "-du {{ db_user }}"
    db_pass_arg:      "-dp {{ db_pass }}"

  tasks:
    - name: install prerequisites
      script: ../script/db_prereqs.sh {{ db_hostname_arg }} {{ domain_arg }} {{ db_ip_arg }}
      register: result
      changed_when: "'Nothing to do' not in result.stdout"

    - name: configure firewall
      script: ../script/db_firewall.sh
      register: result
      changed_when: "'Created symlink' in result.stdout"

    - name: install database server
      script: ../script/db_install.sh {{ db_name_arg }} {{ db_user_arg }}
      register: result
      changed_when: "'postgres now installed' in result.stdout"

    - name: create the application database
      script: ../script/db_create.sh {{ db_name_arg }} {{ db_user_arg }} {{ db_pass_arg }}
      register: result
      changed_when: "'Database now created' in result.stdout"
