---
- hosts: all
  become: true

  vars_files:
    - ../vars/main.yml
  vars:
    db_hostname_arg: "-dh {{ ansible_hostname }}"
    domain_arg: "-d {{ domain }}"
    db_ip_arg: "-di {{ ansible_eth1.ipv4.address }}"

  tasks:
    - name: install prerequisites
      script: ../script/db_prereqs.sh {{ db_hostname_arg }} {{ domain_arg }} {{ db_ip_arg }}
# db_pre_args = [db_hostname, domain, db_ip_arg].join(" ")
# db.vm.provision "db prerequisites", type: "shell", path: "script/db_prereqs.sh", args: db_pre_args

# db.vm.provision "db firewall", type: "shell", path: "script/db_firewall.sh"
#
# db_install_args = [db_name, db_user].join(" ")
# db.vm.provision "db install", type: "shell", path: "script/db_install.sh", args: db_install_args
#
# db_create_args = [db_name, db_user, db_pass].join(" ")
# db.vm.provision "db create", type: "shell", path: "script/db_create.sh", args: db_create_args
